version: '3.8'  # Bu satırı kaldırabilirsiniz (opsiyonel)

services:
  fastapi-app:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:80"
    environment:
      - ORACLE_USER=YourUsername
      - ORACLE_PASSWORD=YourPassword
      - ORACLE_DSN=oracle-xe/XE
    networks:
      - oracle-network

networks:
  oracle-network:
    external: true